name: ci

on: [push]

jobs:
  foundry-lint-check:
    name: Foundry Lint Check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2  # Updated to v2

      - name: Setup Foundry Toolchain
        uses: foundry-rs/foundry-toolchain@v1
        with:
          version: nightly

      - name: Install Dependencies
        run: forge install

      - name: Run Linter
        run: forge fmt --check
        env:
          ETH_FORK_URL: ${{ secrets.ETH_FORK_URL }}
          BSC_FORK_URL: ${{ secrets.BSC_FORK_URL }}
          POLYGON_FORK_URL: ${{ secrets.POLYGON_FORK_URL }}
          ARB_FORK_URL: ${{ secrets.ARB_FORK_URL }}

  foundry-testing:
    name: Foundry Testing
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2  # Updated to v2

      - name: Setup Foundry Toolchain
        uses: foundry-rs/foundry-toolchain@v1
        with:
          version: nightly

      - name: Install Dependencies
        run: forge install

      - name: Run Size Check
        run: forge build --sizes
        env:
          ETH_FORK_URL: ${{ secrets.ETH_FORK_URL }}
          BSC_FORK_URL: ${{ secrets.BSC_FORK_URL }}
          POLYGON_FORK_URL: ${{ secrets.POLYGON_FORK_URL }}
          ARB_FORK_URL: ${{ secrets.ARB_FORK_URL }}

      - name: Run Tests
        run: forge test -vvv
        env:
          ETH_FORK_URL: ${{ secrets.ETH_FORK_URL }}
          BSC_FORK_URL: ${{ secrets.BSC_FORK_URL }}
          POLYGON_FORK_URL: ${{ secrets.POLYGON_FORK_URL }}
          ARB_FORK_URL: ${{ secrets.ARB_FORK_URL }}

      - name: Run Coverage
        run: forge coverage
        env:
          ETH_FORK_URL: ${{ secrets.ETH_FORK_URL }}
          BSC_FORK_URL: ${{ secrets.BSC_FORK_URL }}
          POLYGON_FORK_URL: ${{ secrets.POLYGON_FORK_URL }}
          ARB_FORK_URL: ${{ secrets.ARB_FORK_URL }}

  slither:
    name: Slither Run
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2  # Updated to v2

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1

      - name: Build the contracts
        run: forge build --build-info

      - name: Run Slither
        uses: crytic/slither-action@v0.3.0
        id: slither
        with:
          fail-on: high
          ignore-compile: true
          solc-version: 0.8.19
          slither-args: --checklist --markdown-root ${{ github.server_url }}/${{ github.repository }}/blob/${{ github.sha }}/
          slither-config: "slither.config.json"
